apiVersion: apps/v1
kind: Namespace
metadata:
  name: launch-i-app
---
# frontend service
apiVersion: apps/v1
kind: Service
metadata:
  name: frontend-service
spec:
  app: frontend
type: LoadBalancer
ports:
  - protocol: TCP
    ports: 3000
    targetPorts: 3000
---
# api service
apiVersion: apps/v1
kind: Service
metadata:
  name: api-service
spec:
  app: api
type: LoadBalancer
ports:
  - protocol: TCP
    ports: 8080
    targetPorts: 8080
---
# cache service
apiVersion: apps/v1
kind: Service
metadata:
  name: cache-service
spec:
  app: cache
type: ClusterIP
ports:
  - protocol: TCP
    ports: 6379
    targetPorts: 6379
---
# frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kavi106/launch-1-app:frontend
          env:
            - name: REACT_APP_API_URL
              value: "http://localhost:8080"
# api deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kavi106/launch-1-app:api
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: CACHE_TTL
              value: "3600"
            - name: REPO
              value: "kavi106/pipelines"
            - name: REPO_TOKEN
              value: "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"
# cache deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: kavi106/launch-1-app:cache