apiVersion: v1
kind: Namespace
metadata:
  name: launchiapp
---
# frontend service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: launchiapp
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
# api service
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: launchiapp
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
# frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: launchiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kavi106/launch-i-app:frontendv4
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:8080"
---
# api deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kavi106/launch-i-app:apiv4
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "cache-service"
        - name: REDIS_PORT
          value: "6379"
        - name: CACHE_TTL
          value: "3600"
        - name: REPO
          value: "kavi106/pipelines"
        - name: REPO_TOKEN
          value: "@@ghp_@@Jr@@rGAdIB@@G@@sn0@@pSNB@@XUP70@@o5w@@IiFv@@ne0a@@o@@Af3"